name: yolo-streamlit-env-teste
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - pip
  - matplotlib>=3.2.2
  - numpy==1.26.4
  - opencv-python-headless #  conda install fastai::opencv-python-headless 
  - Pillow>=7.1.2
  - PyYAML==6.0.1
  - requests>=2.23.0
  - scipy==1.13.0
  - torchvision==0.16.0
  - torch==2.1.0
  - tqdm>=4.41.0
  - safetensors==0.4.3
  - ipython==8.15.0
  - streamlit==1.43.2
  - opencv-python==4.11.0.86
  - pip:
      - ultralytics==8.2.85
      